### PR TITLE
add DockerContainer get_archive method

### PR DESCRIPTION
**Pull request by sky-code**
## What do these changes do?

Add missed method for container get archive api

## Are there changes in behavior for the user?

Full backward compatibility

## Related issue number

No

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `changes` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by sky-code** [comment]
Done.

**Comment by barrachri** [comment]
Tests are also very nice to have :)

**Comment by sky-code** [comment]
You can add it, I dont know how to do this for your library

**Comment by asvetlov** [comment]
@sky-code we are striving to keep high code quality for our software.
In practice it means good test coverage along with careful software design and other things.

A Pull Requests which adds a new functionality without any tests for it has a zero chance to be accepted, sorry.
You as contributor should prove that the feature is correct. We are all gentlemans but we do trust tests, not verbal message like "everything works fine on my machine, trust me".
P.S.
You did break Travis CI BTW.

**Comment by sky-code** [comment]
Ok i will add test for this feature.
Funny thing here is that for exactly the same api method `copy` and `put_archive` tests not exists.
Also how have I broken the travis ci?

**Comment by asvetlov** [comment]
Click on 'Details' button on buttom of the page :)
https://travis-ci.org/aio-libs/aiodocker/builds/296547145?utm_source=github_status&utm_medium=notification basically

**Comment by sky-code** [comment]
This is not my impact
image

tests/test_integration.py::test_get_archive PASSED

**Comment by barrachri** [comment]
Thanks @sky-code, travis works fine, I don't get the problem with codecov, I'll give a look tomorrow.

**Comment by sky-code** [comment]
any news on this?

**Pull request merged**
