### PR TITLE
Add user guide for testing

### PR DESCRIPTION
**Pull request by joshua1b**
## What do these changes do?
This commit implements #146 

## Are there changes in behavior for the user?
No.

## Related issue number
#146 

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `changes` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by achimnol** [comment]
How about chaging `test.sh` into a global fixture?

**Comment by joshua1b** [comment]
@achimnol Done.

**Comment by joshua1b** [comment]
It works on local but doesn't works on travis... why?

**Comment by barrachri** [comment]
Could you check your conftest.py?

flake8 fails.

**Comment by joshua1b** [comment]
Done. @barrachri

**Comment by barrachri** [comment]
Something is not [working properly](https://travis-ci.org/aio-libs/aiodocker/jobs/297194439).

```python
E               aiodocker.exceptions.DockerError: DockerError(404, 'no such image: localhost:5001/image:latest: No such image: localhost:5001/image:latest')
```

**Comment by joshua1b** [comment]
hmm.....
It works locally but doesn't work on Travis.
Do I have to make the shell script to global fixture?
Can't we just separate local test and Travis ci?

**Comment by joshua1b** [comment]
If you create a separate script for local testing, you can pass both the local test and the travis test.

**Comment by barrachri** [comment]
Thanks @joshua1b!

**Pull request merged**
