### PR TITLE
resolve errors and warnings

### PR DESCRIPTION
**Pull request by thehesiod**
- fix named parameter
- fixed missing case
- fix pep warning

### CODE REVIEW

**Comment by jettify** [comment]
Changes looks good, but we do not have test to hit changed lines, could you please add one.

**Comment by thehesiod** [comment]
btw, there's a problem with `containers.run`.  It's possible that `create` succeeds, but `start` fails, in which case the caller will never get the container ID to be able to delete it.

**Comment by barrachri** [comment]
Hello @thehesiod, you mean that `await container.start()` could raise an error?

**Comment by thehesiod** [comment]
ya

**Comment by barrachri** [comment]
What about catching the error and returning the container object?

**Comment by thehesiod** [comment]
there error can be raised here: https://github.com/aio-libs/aiodocker/blob/master/aiodocker/containers.py#L77  how would you return the container object?

**Comment by thehesiod** [comment]
whoops, the error can be raised from in here: https://github.com/aio-libs/aiodocker/blob/master/aiodocker/containers.py#L78  how would you return the container?  The only thing I can think of is stashing the container in the exception object.

**Comment by barrachri** [comment]
I think it's not up to us to remove the container but I would pass the id of the container somehow.
Actually we can put it inside the exception.

**Comment by thehesiod** [comment]
ya, so just FYI to you guys :)

**Comment by barrachri** [comment]
LGTM

**Comment by jettify** [comment]
Should we create ticket for container id issue? I think putting container id into exception is good idea

**Comment by barrachri** [comment]
Done: https://github.com/aio-libs/aiodocker/issues/128

**Comment by barrachri** [comment]
THANKS @thehesiod !

**Pull request merged**
