### PR TITLE
Fix #189: Add initial support for networks

### LINKED ISSUE #189: Add support for docker network
## Long story short

* Expected behaviour:
* Actual behaviour:

### PR DESCRIPTION
**Pull request by apatrushev**
## What do these changes do?

Add initial and thin networks support (same as volumes).

## Are there changes in behavior for the user?

New attribute available in docker object - `networks`.

## Related issue number

#189 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `changes` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by apatrushev** [comment]
Seems that tests are broken by unrelated reasons.

**Comment by barrachri** [comment]
Hi @apatrushev, check flake8 `aiodocker/networks.py:51:9: F841 local variable 'response' is assigned to but never used`

**Comment by apatrushev** [comment]
Sorry for such long story in this PR - I was not sure about tests organization and how to run them locally. Now everything should be fine.

**Comment by barrachri** [comment]
thanks @apatrushev !

do you mind adding the docstrings for each method? Even something short is fine.

**Comment by barrachri** [comment]
also can you add tests for `connect` and `disconnect`?

**Comment by apatrushev** [comment]
Sorry, I think that current abstraction is very low level and comments will be useless. Almost all methods in this library are thin wrappers around Docker Engine API calls and best docstring is a link to Docker Engine API.

I will add tests for [dis]connect methods.

**Comment by apatrushev** [comment]
Ok. I added the tests for [dis]connect network method. Now tests definitely was broken by unrelated reasons.

**Comment by barrachri** [comment]
Thanks @apatrushev !

**Pull request merged**
