### PR TITLE
Fix auth registry (Close #172)

### LINKED ISSUE #172: auth with registry doesn't work
## Long story short
The current implementation to auth with a registry doesn't work.

If you don't provide all the information you need

```
assert 'username' in auth
assert 'password' in auth
assert 'email' in auth
assert 'serveraddress' in auth
```
And you just need username and password.

https://github.com/aio-libs/aiodocker/blob/master/aiodocker/utils.py#L247

Also compared to the dockerpy version we have lots of more lines.

https://github.com/docker/docker-py/blob/master/docker/auth.py#L158

### PR DESCRIPTION
**Pull request by barrachri**
## What do these changes do?

Fix issue #172 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `changes` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
Is it possible to add a test to make sure that everything is function correctly?

**Comment by barrachri** [comment]
The best way is to test against a registry that needs authentication.

What do you think about testing using the docker hub?

We can setup a free account and push an image there where you require username/password.

The other way would be just to check the headers and see what's inside.

**Comment by asvetlov** [comment]
I have no strong preference.
@aio-libs/aiodocker-committers what do you think?

**Comment by cecton** [comment]
Looks good to me but I wonder if we still need the rest of this method.

**Comment by barrachri** [comment]
@cecton I didn't have time to look through, but I guess no.

**Comment by barrachri** [comment]
@asvetlov I think is ok now, can you merge it (no idea why coverage is negative....)?

**Comment by cecton** [comment]
It's because there are less lines in the code in general and they were lines covered. So in the end you have proportionally less covered lines of code.

We should be able to ignore this check to merge. It's especially not relevant while refactoring. Otherwise we're going to accumulate old PRs like that.

**Comment by barrachri** [comment]
Thanks for the explanation @cecton.

**Pull request merged**
