### PR TITLE
add local Dockerfile and tar

### PR DESCRIPTION
**Pull request by barrachri**
Currently for some tests we use Dockerfile [hosted](https://github.com/aio-libs/aiodocker/blob/master/tests/test_images.py#L9) outside of this repository.

I'd like to put everything inside the official repo and add a tar to add a test about using remote tar as a local context.

### CODE REVIEW

**Comment by asvetlov** [comment]
I'd like to have `Makefile` in the project like many other `aio-libs` libraries do.
One obvious command is `make test`, other is `make flake` maybe.

I think new commands for making docker image and tar makes sense at least from visibility perspective.

**Comment by asvetlov** [comment]
IIRC @achimnol prefer Alpine images for their light weight.
Maybe we should do it too here?
Default Python image is based on Jessie but there is `3.6.1-alpine` tag also.

**Comment by barrachri** [comment]
To make the tar it makes sense, but related the docker image it will be build only during the test phase.

About the makefile, something like [this](https://github.com/aio-libs/aiohttp/blob/master/Makefile)?

**Comment by asvetlov** [comment]
Yes, but you could start from very simplified version with a command or two.

**Comment by asvetlov** [comment]
IIRC @achimnol prefer Alpine images for their light weight.
Maybe we should do it too here?
Default Python image is based on Jessie but there is `3.6.1-alpine` tag also.

**Comment by barrachri** [comment]
Something like [this](https://github.com/barrachri/aiodocker/blob/1ad7b8fe9cd6df82d583f6f384a75a5f4d128740/Makefile)?

**Comment by jettify** [comment]
Changes looks good, you will update tests to use this Dockerfile and archive in next PR?

**Comment by barrachri** [comment]
Yes, that's the plan.

I think I am going to change the images to alpine with a new commit.

Is this ok?

After this I will merge.

**Comment by jettify** [comment]
sure

**Pull request merged**
