### PR TITLE
remove strip with chunk data, fix sometimes drop char

### PR DESCRIPTION
**Pull request by gaopeiliang**
Question:    with log , sometimes I have found the log text has no '\n',  it is different from docker log cli and not pretty

Fix:    remove the strip handle with chunk data from http,  it maybe drop '\n' or ' ' if chunk data end with it!

### CODE REVIEW

**Comment by barrachri** [comment]
Hi @gaopeiliang,

what is the reason for this pr?

**Comment by gaopeiliang** [comment]
I have update the PR comment!

**Comment by barrachri** [comment]
Thanks @gaopeiliang.

I don't really know if this is what we want.

Given that we receive log lines, I am not so sure we want to consider them like a `raw` stream.

@achimnol what do you think?

**Comment by gaopeiliang** [comment]
when receive logs ,  every log chunk data  will append to [],  Apply strip func to chunk data will drop '\n' if chunk data end with '\n'  , like below code

`async def multiplexed_result(response, follow=False, is_tty=False,
                             encoding='utf-8'):

    # if is_tty is True you get a raw output
    log_stream = MultiplexedResult(response, raw=is_tty)

    if follow:
        return _DecodeHelper(log_stream, encoding=encoding)
    else:
        d = []
        async for piece in _DecodeHelper(log_stream, encoding=encoding):
            d.append(**piece.strip()**)
        return d`

**Comment by travigd** [comment]
@barrachri 
At the very least, I think this should be `.rstrip("\r\n")` since the current version messes with indentation of logged lines.

E.g.
```
def foo(bar):
    print(bar)
```
becomes
```
def foo(bar):
print(bar)
```
when `cat`'d.

**Comment by barrachri** [comment]
Thanks @travigd makes sense.

@gaopeiliang what do you think?

**Comment by barrachri** [comment]
Fixed by #247.

**Comment by gaopeiliang** [comment]
I am sorry so later ....

Raw message break into some chunk data message transmit,  this code we just join all the chunk data.
Eg:

``` python
def foo(bar):
      print(bar)
```

the message maybe "def foo(bar):\n       print(bar)" ! 

when this  message break into :
```python
    chunk_1='def foo', chunk_2='(bar):\n    print(bar)' 
```
 use strip() , strip('\n'), rstrip('\n'),   it is OK , because nothing to do.

when this message break into 
```python
chunk_1='def foo(bar):\n', chunk_2='     print(bar)'
```
 use strip(),  it will drop '\n' and '   ', all message will like this:
 ```python
 def foo(bar):print(bar)
 ```
use rstrip('\n'), it will drop '\n' , all message will like this:
```python
def foo(bar):
print(bar)
```
------------
so it mybe better, just join the chunk data, do nothing strip.... 

@travigd @barrachri

**Comment by barrachri** [comment]
Thanks @gaopeiliang do you have a copy of the log that can cause a problem?

**Comment by gaopeiliang** [comment]
Example docker log print by this program:
```
    def main():
        print '\n'*100 ,
```
1.  DockerContainer.log(stdout=True)  not work correctly , it will drop '\n', almost everying
2. Now turn to the code 
```
logs = await DockerContainer.log(stdout=True)
print(''.join(logs))    // output wrong

logs = []
async for data in DockerContainer.log(stdout=True, follow=True):
    logs.append(data)
print(''.join(logs))   // output correct
```
The difference output , just because when not follow , we iter and join chunk data with strip.

3. how we find the problem in pre PR commit with strip() by us ?
    
     we use docker log to filter some multi Line key words with Reg in our CI test,  sometimes Case 
     failed in drop '\n'.

**Comment by barrachri** [comment]
I see, so the best solution would be to leave the raw output for:

```
logs = await DockerContainer.log(stdout=True)
print(''.join(logs))    // output wrong
```

basically changing this only to return the `piece`:

https://github.com/aio-libs/aiodocker/blob/5a8c5a6431424bbc12a631a3d1da14feb0853197/aiodocker/multiplexed.py#L79

**Comment by barrachri** [comment]
Thanks @gaopeiliang!

**Pull request merged**
