### PR TITLE
Fix #190: Add objects DockerConfigs and DockerSecrets

### LINKED ISSUE #190: Add support for Docker secret
## Long story short

* Expected behaviour:
* Actual behaviour:

### PR DESCRIPTION
**Pull request by akiuni**
## What do these changes do?

Add support of swarm secrets and configs, based on the DockerService object

## Are there changes in behavior for the user?

New objects have been added but no other changes

## Related issue number

#190 

## Checklist

I didn't write neither unit tests nor documents yet. I'll do that if the team approves that code.

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `changes` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by akiuni** [comment]
I don't know how to proceed to pass "codecov/patch Expected — Waiting for status to be reported" and "codecov/project Expected — Waiting for status to be reported" ...

**Comment by asvetlov** [comment]
This pull request has been mentioned on **aio-libs**. There might be relevant details there:

https://aio-libs.discourse.group/t/is-aio-libs-aiodocker-still-supported/237/1

**Review by asvetlov — APPROVED** [review]
LGTM

**Comment by asvetlov** [comment]
Thanks, @akiuni 
Sorry for the late reply.

**Pull request merged**
