### PR TITLE
Fix params passing in Docker API calls

### PR DESCRIPTION
**Pull request by yannickperrenet**
Fixes passing JSON structures as params.

## What do these changes do?

Fixes calls like:
```python
client.containers.list(filters={"network": [network]})
```
where the kwarg passed to `containers.list` (and other functions that query the Docker engine) is a JSON structure (for reference see the [Docker engine API](https://docs.docker.com/engine/api/v1.41/#operation/ContainerList)).

## Are there changes in behavior for the user?

Users can now pass JSON-like params.

## Checklist

- [X] I think the code is well written
- [X] Unit tests for the changes exist
- [X] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `changes` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by yannickperrenet** [comment]
Is there anything I need to change in the PR?

@asvetlov @achimnol

**Comment by akiuni** [comment]
> Is there anything I need to change in the PR?
> 
> @asvetlov @achimnol

Hello @yannickperrenet , I'm stuck as the same point in my PR ( https://github.com/aio-libs/aiodocker/pull/596 ) , do you have some clue ?

**Comment by yannickperrenet** [comment]
Hi @akiuni, all I can tell is that this repository is not actively worked on at the moment/any more. Last activity seems to be around December 2020.  

I am playing the waiting game and using my fork for the time being. Don't think there is enough interest to maintain a community fork of this project (at least not from my side). Hope that helps.

**Comment by akiuni** [comment]
Hello Yannick

Thank you for your answer. From my side, I would be interrested to maintain
a community fork of this project if this repo isn't worked anymore.
I will use my fork as well in the meantime (and you can push your PR on my
fork if you want so)

Best regards
Julien



Le ven. 2 juil. 2021 à 21:12, Yannick Perrenet ***@***.***> a
écrit :

**Comment by asvetlov** [comment]
This pull request has been mentioned on **aio-libs**. There might be relevant details there:

https://aio-libs.discourse.group/t/is-aio-libs-aiodocker-still-supported/237/1

**Review by asvetlov — APPROVED** [review]
LGTM, thanks!

**Comment by auspex** [comment]
I'd just like to point out that this fix still does not make `aiodocker` work quite like the synchronous `docker`, but I think that's more of a bug in the latter.

The fix ensures that:
```
client.containers.list(filters={"network": [network]})
```
works (and is the way the [Docker API documentation](https://docs.docker.com/reference/api/engine/version/v1.49/#tag/Container/operation/ContainerList) says it should be), but the synchronous client permits:
```
client.containers.list(filters={"network": network})
```

It took me a while to figure out why I was still getting `aiodocker.exceptions.DockerError: DockerError(400, 'invalid filter')`.
I don't think `aiodocker` should be "fixed" to be entirely consistent, but this note might help others.

**Pull request merged**
